version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  postgres-data:
