# Set app name here or use -a
# app = 'app_name'
primary_region = 'cdg'
console_command = '/rails/bin/rails console'

[http_service]
  internal_port = 3000
  force_https = true
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512mb"

[checks]
  [checks.status]
    grace_period = '5s'
    interval = '10s'
    method = 'get'
    path = '/up'
    port = 3000
    protocol = 'http'
    timeout = '2s'
    type = 'http'

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
